### ISSUE TITLE
Convert to rspec?

### ISSUE THREAD

**Issue by ppeble** [holidays/holidays#107]
What are people's thoughts about the current test suite? In the process of refactoring I am adding a bunch of new tests and I'm starting to wonder if I should spend the time to convert us to rspec. 

I'll admit that I am partial to it over Test::Unit. It has a lot of additional features that I have come to rely upon. I'm really torn, though, because it's a lot of work and we already have working tests.

Looking for thoughts from others to help me decide.

**Comment by johnnyshields** [comment]
+1 to Rspec, it's the way to go and most gems are using it.

**Comment by ptrimble** [comment]
I *am* going to do this but I have to push it off. I'm basically performing a complete rewrite of this gem and I just can't bring myself to go back and redo all of the existing tests yet. I'll leave that for a future enhancement and I'll leave this issue open in the meantime.

**Comment by ptrimble** [comment]
Just want to say that I really really really want to switch. Finishing up my tests without rspec has been hell.

**Comment by ttwo32** [comment]
+1 to Rspec.

**Comment by chinito** [comment]
+1 from me too

**Comment by jonathanpike** [comment]
I'm going to be the dissenting voice in this discussion and say that I think it would be better to keep the  test suite as-is.  While rspec's DSL is great and it has a lot of features, the simplicity and default "Rubyness" of Test-Unit is much easier to get my head around.  Plus, converting the test suite would be a lot of extra work.  I guess it comes down to a cost/benefit analysis -- are the features you rely on in rspec worth the pain of re-writing the entire suite?

**Comment by ppeble** [comment]
Thanks for the feedback, everyone. I'm gonna leave this open for a bit but...I'm basically coming to terms with the fact that, as a new dad and someone with a fulltime job, I just don't think I'll ever truly have the bandwidth to do this entirely unnecessary change. And as @jonathanpike pointed out, what are we really gaining? Yes, I love rspec and I like it more than Test-Unit, but I don't love it so much so that I would be willing to spend nights re-writing already working tests. 😉 

As I said I'll leave this open for more discussion but unless someone else is willing to step up and make the transition I don't think it's gonna happen.

**Comment by ppeble** [comment]
Going to go ahead and close this.  TestUnit is good for us! It has served us well. Unless a compelling PR comes in we won't be switching.
