### ISSUE TITLE
Add new region - Bulgaria

### ISSUE THREAD

**Issue by tyrmyk** [holidays/holidays#109]
Hi,
It will be very nice if the Bulgarian holidays are added. I've prepared "bg.yaml" that is tested. It seems it is working fine. The problem is that the Orthodox Easter is calculated according the Julian calender -> http://en.wikipedia.org/wiki/Easter. I found this functionality implemented in project https://github.com/Loyolny/when_easter, so I used it. Maybe you could implement the same code for the Orthodox Easter calculations or just use the plug in.
How can I send you the yaml file?
Best regards!

**Comment by ptrimble** [comment]
Hm, that is interesting! Let me take a look at this and see how we can integrate Orthodox Easter. I completely agree that just having the Julian calendar Easter is not enough. 

I might push it back a bit while I refactor the app...right now the Easter calculations are right in the main lib/holidays.rb file. I would like to split Easter calculations out. When I split them out it should be easier to specify the different types of Easter calculations.

For the yaml file I would appreciate opening a PR against your branch. That way we can take a look and offer feedback. Here are some instructions (let me know if I can make them more clear): https://github.com/alexdunae/holidays#how-to-contribute

**Comment by tyrmyk** [comment]
My colleagues and me tried creating a fork of your project and creating a pull request with the changes we made. Unfortunately the system did not allow to publish/sync/upload the PR. Maybe it is due to our free accounts or we are missing some steps. Could you give us advice how to do it? We could send you the package by e-mail or you can get it from here: https://www.dropbox.com/s/wqpci1fptisqa4u/holidays-1.2.0.zip?dl=0

**Comment by ptrimble** [comment]
Hi @tyrmyk , hm, you should be able to open a PR with a regular free account on Github. Did you follow these instructions? https://help.github.com/articles/creating-a-pull-request/

**Comment by ptrimble** [comment]
I'm going to go ahead and close this issue since we have an open PR and I am (finally) on top of it. Sorry again to you and your colleagues for my absolutely dreadful response time. I feel awful.

For posterity here is the PR: https://github.com/holidays/holidays/pull/117
