### ISSUE TITLE
Improve integration tests

### ISSUE THREAD

**Issue by ppeble** [holidays/holidays#133]

**Comment by ptrimble** [comment]
I'm souring on this idea. I am going to leave this open but rename it. We need better top-level integration style tests but I don't think we should do it via cucumber. And I really don't think that we should worry about date-specific stuff. The definitions should be validated by their own tests. The overall integration tests should just confirm that the public API is still valid and not breaking.

**Comment by ppeble** [comment]
I'm going to close this. We have 'integration' tests that we can improve upon but I don't think it needs its own issue.
