### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by ptrimble** [holidays/holidays#170]
I know this is a small project but I feel strongly that a Code of Conduct should be added if for no other reason than to indicate my overt support for a friendly, open, and cooperative open source community.

I'll be adding something along the lines of the [Contributor Covenant](http://contributor-covenant.org/) in the coming weeks. I'm only waiting because I have a good head of steam going in my current work and don't want to lose that momentum. :smile:

**Comment by ttwo32** [comment]
:smile:

**Comment by ptrimble** [comment]
Added!
