### ISSUE TITLE
German informal holidays

### ISSUE THREAD

**Issue by knut2** [holidays/holidays#173]
Hello,

I'm missing some (informal) holidays in the definitions for Germany, and modified the de.yaml definition in  https://github.com/knut2/holidays/commit/d3641f9c41890824d0d6c4821c93b468f63b6bb5

But I'm not sure if my changes fit the logic of the definitions in the gem.

Before I post a pull request I want to ask, if my changes would fit the general logic:

* easter sunday  and pentecost sunday are missing yet, I would add them as informal holidays.
* Carnival is missing, I would add them as informal holidays in de_bw, de_by, de_he, de_nw, de_rp, de_sl, de_sn.
* Fronleichnam (Corpus Christi)  is a holiday is some regions of Sachsen and Thüringen (de_sn+de_th). I would add it to the regions de_sn_aux and de_th_aux (like the Friedensfest for de_by_aux)
* The  Reformationstag (Reformation Day) is a school free day in Baden-Württemberg (de_bw, no holiday, only school free). I would add it as an informal holiday.
* I would add Christmas Eve and Silvester as informal holidays.

And the last topic:
The  Reformationstag (Reformation Day)  is a public holiday in 2017 for whole Germany (500 years of reformation). Is there a logic for one-time-holidays?

I tried to use year_ranges with limited, but it  did not work correct. are there any hint how to use it.

**Comment by ttwo32** [comment]
Hello @knut2 

>> Is there a logic for one-time-holidays?
Yes,I have added valid year feature https://github.com/holidays/holidays/pull/162 .

I have written how to use the feature in conversations https://github.com/holidays/holidays/pull/147 ,
and developed testing-code at test_custom_year_range_holiday_defs.yaml.

If you want to add one-year-holiday, you should use limited option.

example ( 2016,2018,2019 are limited holiday years at june 24th.)
```
months:
  6:
  - name: limited_year
    regions: [your religion]
    mday: 4
    year_ranges:
      - limited: [2016,2018,2019]
```

Sorry, I don't know other quesions answer.

**Comment by ptrimble** [comment]
Thank you for the PR! I will take a look at this in the coming week. Sorry for the delay...I'm buying a house and so my personal time is very much affected by that process. I hope to get a PR out today for another issue and then begin tackling the open PRs and answering questions.

Thanks for your patience!

**Comment by ptrimble** [comment]
Oh, oops! I thought this was a PR! How embarrassing. :smile: 

I will still try to get to answering your questions this week so we can agree on a course of action.

**Comment by knut2** [comment]
No porblem, I wanted first to solve some problems before I post my PR. 

In meantime I'm quite sure I detected a bug with year_ranges. I will open a new issue with a detailed description.

**Comment by ptrimble** [comment]
Fantastic, thank you. That's a newish feature so it's entirely possible that there are things that we still need to shake out.

**Comment by knut2** [comment]
I made a pull request with my changes: #175

**Comment by ptrimble** [comment]
This was merged and will be available in a new version shortly. Thanks again @knut2!
