### ISSUE TITLE
`load_custom` method should not return the list of custom methods

### ISSUE THREAD

**Issue by ptrimble** [holidays/holidays#186]
Currently the `load_custom` method simply returns the last thing we did in the method, which is to add the `custom_methods` to the in-memory repository. This is confusing and dumb. We should do one of the following:

* return 'nil'
* return the holidays that were just added so the user can see what was successfully loaded

I'm kinda leaning towards number 2 at the moment.

**Comment by ptrimble** [comment]
Thinking about it more, this should go with my current refactor tied to https://github.com/holidays/holidays/issues/144 ([PR here](https://github.com/holidays/holidays/pull/179)). I highly, highly doubt that changing the response will break anyone's code but it *is* technically a breaking change. I should put them all together.

**Comment by ttwo32** [comment]
I prefer number 2. Because i can see the holiday what was successfully loaded. When method returned nil , i would think method was failed or conditions were invalid.

**Comment by ptrimble** [comment]
👍 Great, thank you! That is what I was thinking as well.

**Comment by ptrimble** [comment]
This has been handled by the latest commit in https://github.com/holidays/holidays/issues/144. Gonna leave this open until it's merged.

**Comment by ptrimble** [comment]
Okay! v4.0.0 is out!
