### ISSUE TITLE
Romanian definition file is titled as Austrian definitions

### ISSUE THREAD

**Issue by jonathanpike** [holidays/holidays#199]
This is a super small issue, which you can see [here](https://github.com/holidays/holidays/blob/master/definitions/ro.yaml#L1).

Should be corrected to say **Romanian Holiday Definitions for the Ruby Holiday gem.**

**Comment by ptrimble** [comment]
Thanks! I went ahead and updated it in commit https://github.com/holidays/holidays/commit/f137baae1194a9fcd86abd6688f0243ff8e1cae0. Going to go ahead and close this out, let me know if you find anything else!
