### ISSUE TITLE
Wiki for this project is out of date

### ISSUE THREAD

**Issue by ptrimble** [holidays/holidays#206]
I didn't even realize that there *was* a wiki for this repository. I'll clean it up and make it point to the repo since we now mostly have good READMEs.

**Comment by espen** [comment]
Just delete the wiki?

**Comment by ptrimble** [comment]
@espen Yeah, not a bad idea. Do you think the README and related docs do a good enough job explaining stuff? I personally think so but...I also spend a lot of time in the code, so my opinion is kinda biased.

@ttwo32 Any thoughts on deleting the wiki? Is it necessary?

**Comment by espen** [comment]
The wiki info is outdated (thus confusing) and it seems like https://github.com/holidays/definitions/blob/master/SYNTAX.md gives a good explanation.

**Comment by ptrimble** [comment]
I'm inclined to agree. Good argument.

@ttwo32? You agree?

**Comment by ttwo32** [comment]
@ptrimble Sure, i agree.:+1:

**Comment by ptrimble** [comment]
Done! Closing this issue, thanks @ttwo32 and @espen!
