### ISSUE TITLE
Friday Before the AFL Grand Final 2016 isn't returned as a holiday

### ISSUE THREAD

**Issue by daBayrus** [holidays/holidays#211]
running `Holidays.on(Date.civil(2016,9,30), :au_vic, :observed)` returns an `empty array []` .. 

expected output is `[{:date=>Fri, 30 Sep 2016, :name=>"Friday before the AFL Grand Final", :regions=>[:au_vic]}]`

**Comment by ptrimble** [comment]
Thank you for the report! I will look into this and figure out what is going on. We have a custom calculation for this specific holiday, there must be something wrong.

I'm going to google for it but I assume you live in Australia. Do you have a link to a resource that specifies the exact rules for this holiday?

**Comment by ptrimble** [comment]
Oof, I *just* looked at what we are doing. It's obvious why this does not work:

```ruby
      if year == 2015
        Date.civil(2015, 10, 2)
      end
```

This is only set up for 2015. At the time I must have assumed that this was a one-off holiday but it apparently happens every year? @ghiculescu if you are willing can you shed more light on this holiday? As an American I'm left googling for information,which might not be reliable.

**Comment by ghiculescu** [comment]
Looks like it's a permanent thing now - http://www.business.vic.gov.au/victorian-public-holidays-and-daylight-saving/victorian-public-holidays - though on a different date each year. I'm on the road but can update it when I'm back. Or either of you guys can - it's just a matter of hard coding in another date for this year. 

Alex Ghiculescu
alex@tanda.co

**Comment by ptrimble** [comment]
Thanks @ghiculescu! I went ahead  and added 2016.  I don't see anything for 2017 yet so I'll just wait, I suppose. Here is the PR: https://github.com/holidays/holidays/pull/214

**Comment by ptrimble** [comment]
Merged, I will release sometime shortly. Thanks!
