### ISSUE TITLE
`LocalJumpError` when the period is too long

### ISSUE THREAD

**Issue by ironsand** [holidays/holidays#225]
Hi,

I got a error when I run `Holidays.between(Date.civil(2000, 1, 1), Date.civil(2018), :jp)`

```
LocalJumpError: unexpected return
from /Users/ironsand/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/holidays-4.6.0/lib/generated_definitions/jp.rb:116:in `block in custom_methods'
```

but if I change `2000` to `2005`, then it works fine.

```
Holidays.between(Date.civil(2005, 1, 1), Date.civil(2018), :jp)
```

I'm happy if I can use it from `2000`. Thanks

**Comment by ptrimble** [comment]
Thanks for the report @ironsand! We will look into it this week. If we can figure it out quickly I'll do a pre 5.0 bug release so you can get the fix without having to manage a major version bump.

@ttwo32 Can you also look into this since it is using `jp` holidays?

**Comment by ttwo32** [comment]
Hi @ironsand !! Thanks for the report.I will look into this issue .So please wait .:D

@ptrimble Sure.I will check this issue.:smile:

Side note: I am happy that this gem is used in japan.:D

**Comment by ptrimble** [comment]
@ironsand I am releasing 4.7.0 shortly, which should have this issue resolved. Thanks again for reporting!

**Comment by ttwo32** [comment]
@ironsand Thanks again!!  Please repporting again when some issues happen.:smile:
ありがとうございました‼また何かあれば報告してください！！

**Comment by ironsand** [comment]
@ptrimble @ttwo32 Great! Thanks a lot!
