### ISSUE TITLE
Issue in identifying holidays for region :ca when used in Rails application in production mode

### ISSUE THREAD

**Issue by ff-sgupta** [holidays/holidays#23]
The gem is working perfectly fine in development mode when cache_classes is set to false. However, when in production mode gem fails to recognize the Canadian holidays e.g New year's day. I made some initial investigation and found that.

1. In production mode holiday definitions for US (holidays/us.rb) is getting loaded by default which is not happening in development mode
2. In us.rb we have regions specified as [:us, :us_dc, :ca].
3.  Due to this, when we try to find a holiday for :ca, the holidays/ca.rb is not loaded since in @@regions we have  [:us, :us_dc, :ca]

Line 342 of holidays.rb file
raise UnknownRegionError unless regions.all? { |r| r == :any or @@regions.include?(r) or begin require "holidays/#{r.to_s}"; rescue LoadError; false; end }

I believe we should we should have this modified to load the holiday definitions file if not loaded as follows (Just changed the order of condition)

raise UnknownRegionError unless regions.all? { |r| r == :any or begin require "holidays/#{r.to_s}"; rescue LoadError; false; end or @@regions.include?(r)}

Also, why do we have :ca region specified in holidays/us.rb holiday definition file?

**Comment by ptrimble** [comment]
Small update, I am in the process of refactoring the codebase so that we don't have a giant single file that contains all of our logic. I'm hoping that one of two things happens during this process:

1) I figure out what is causing problems like this while refactoring
2) Once the codebase is split up it will be easier to diagnose problems like this.

**Comment by ptrimble** [comment]
I've merged in v4.0.0, which is a large refactor. This is my next target since it is now the oldest bug that I have inherited.

**Comment by ptrimble** [comment]
Okay! I spent some time looking at this and testing locally and as far as I can tell the core problem has been resolved. The code that handles loading of regions and definitions has changed significantly. I am going to go ahead and close out this issue. Please open a new issue if the problem (or a similar one) persists.

As an aside, once I work through the current crop of issues I am going to A) spend some time with internal refactoring for clarity and B) look at the north american informal holidays. As Alex mentioned it is a bit confusing currently.
