### ISSUE TITLE
Load all regions on demand

### ISSUE THREAD

**Issue by espen** [holidays/holidays#230]
```
irb(main):001:0> require "holidays"
=> true
irb(main):002:0> Holidays.available_regions
NameError: uninitialized constant Holidays::REGIONS
```

Is there any way to load all regions in v5 without calling a specific date method?

**Comment by ptrimble** [comment]
😱 

That is a pretty egregious oversight, isn't it. I apologize!

I will work this week on finding a solution so that you can 'preload' everything if needed so we can satisfy both use cases. Sorry again!

**Comment by ttwo32** [comment]
Oh．．． 😱
@espen Sorry again.

**Comment by espen** [comment]
No worries, I'm using the previous version which works perfectly. Thanks for the work on a very useful gem :)

**Comment by ptrimble** [comment]
Sorry that this is taking so long! These last two weeks have been really crazy for me, personally, so things have been slower than I would like. I *am* still investigating this but I'm not entirely sure when I'll have an answer. Thanks for your patience!

**Comment by ptrimble** [comment]
Actually! :nerd_face: 

I realized that I could take some previous code and implement this. What do we think @ttwo32 and @espen? 

PR: https://github.com/holidays/holidays/pull/233

**Comment by ttwo32** [comment]
@ptrimble I agree.Thanks for your work.:+1:

**Comment by ptrimble** [comment]
@espen Does this new `load_all` method work for you? Is the name clear?

**Comment by ptrimble** [comment]
@espen Friendly poke! I would like to make sure this kind of method works for your use case before I add it to our API. Once it's in there I won't be able to change/remove it without a major version bump. 😄

**Comment by espen** [comment]
Sorry been busy
![14700920_10157585354840092_3642189891317902741_o](https://cloud.githubusercontent.com/assets/32258/19628336/adacdfac-995b-11e6-98d0-ea203467b2cb.jpg)


I tried out this branch in my project locally and it's working great with `Holidays.load_all` in an initializer. Thanks!

**Comment by ptrimble** [comment]
Ooof, that's beautiful. Where is that? I'm very jealous. 😃 

No worries at all, it's just been sitting. No big deal. Thanks for the feedback!
