### ISSUE TITLE
Canada yaml definitions updated, but not generated definitions

### ISSUE THREAD

**Issue by slucaskim** [holidays/holidays#244]
Hello, I found that some weekend rules for Canada national holidays were wrong in the generated definition, so I went to the yaml file in the definitions repo. I found that the issue was actually fixed there 6 days ago, but the generated definition in the holidays repo hasn't yet been updated. Is this something you guys have to do; what do we do in this scenario?

**Comment by ptrimble** [comment]
Yes, sorry, that's on me. Right now it is something I need to do and I just lost track of it this weekend. I'll get a release out this evening so we're all up to date.

**Comment by slucaskim** [comment]
No problem, if it's ok with you, I can try making a PR for this?

**Comment by ptrimble** [comment]
I'm releasing 5.2.0 right now, which will include the updated definitions. Sorry for the delay!
