### ISSUE TITLE
subregions get lost if more than one underscore

### ISSUE THREAD

**Issue by chinito** [holidays/holidays#250]
So, the following happens:

:de contains all holidays from Germany, correct
:de_by contains all holidays from Germany and those from Bavaria, correct
:de_by_aux contains all holidays from Germany, and the one from Augsburg, but looses all Bavarian Holidays.

So xx_yy_zz is equally treated like xx_zz. They both only inherent from the first parent, but not from the second.

I now see two possibilities. First, we could fix that programmatically in this gem. I don't know, how complicated this is and hope to find out(already spent some hours on that...)
Second, we introduce a new region like de_by, de_sn with name db_by_a. We the put all db_by holidays there, plus Friedensfest on 8th of August.

**Comment by ptrimble** [comment]
This is an excellent catch! I am reviewing your PR now, thank you! I'll get back to you. ❤️
