### ISSUE TITLE
Failed test  for  `test_year_holidays_without_specified_year`

### ISSUE THREAD

**Issue by achr3f** [holidays/holidays#254]
<img width="778" alt="capture d ecran 2016-12-27 a 11 47 32" src="https://cloud.githubusercontent.com/assets/1219738/21498182/ab49667a-cc2a-11e6-8c81-61ffd558d7ff.png">

the `Holidays.year_holidays([:ca_on])`  return always an empty Array

**Comment by ttwo32** [comment]
Thank you for reporting this issue.:)
I had known this problem before 4 days ago. 
Last holiday of :ca_on region in this year is Dec 26.Between Dec.27th and Dec.31th in each year ,this test case will fail.
I will fix this issue so please wait few days.:)

**Comment by ttwo32** [comment]
@achr3f I have fixed this issue. Please checkout HEAD version from master .:)

**Comment by achr3f** [comment]
@ttwo32   Thx,  good job
