### ISSUE TITLE
Clean up coverage comments

### ISSUE THREAD

**Issue by ppeble** [holidays/holidays#262]
This has been happening for a while now but something changed somewhere and now we are receiving nearly 10 emails and GH comments per test run on Travis CI. I think it's doing it once per version of Ruby we are using. This is dumb.

I think the comments are good but we should only show it once.

**Comment by ttwo32** [comment]
I agree with your thoughts.
It is a little noisy.

When I have timem, I will investigate this too.

**Comment by ppeble** [comment]
@morrme pointed out that we are not alone: https://github.com/lemurheavy/coveralls-public/issues/491

**Comment by morrme** [comment]
So far the only resolution seems to turn off  the comment "feature", assuming this setting is still current: 
https://github.com/lemurheavy/coveralls-public/issues/25#issuecomment-72534212

**Comment by ppeble** [comment]
This is excellent info. Thank you! 

However...I am kinda souring on Coveralls. I don't know if we need it. It's a bit cumbersome and provides a lot of features that we don't use at all. I really just want a check that we don't fall below a certain threshold. 

SimpleCov has this feature. I can, for example, set it so that if the overall coverage falls below 99% then the tests themselves will fail. That means we lose the comments in our PRs but...as you suggested, I would already lose them if I don't want this spam.

I'm going to have to think about this. I wonder if we can just use [this from SimpleCov](https://github.com/colszowka/simplecov#minimum-coverage)?

**Comment by ppeble** [comment]
Side note: what I suggested is what we do at work @sittercity. Tests won't even pass locally if your test coverage doesn't pass a certain threshold (in our case we aim for 100%).

**Comment by morrme** [comment]
@ppeble  It looks like that setting would work. I edited the original post to mention that some people "solved" the issue by moving to another provider (codecov).

**Comment by morrme** [comment]
@ppeble ahhh! sitter city??? you work with some seriously amazing humans. i owe so, so much to them. now i'm even more honored to support!!!

**Comment by ppeble** [comment]
❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ 

It's a pretty great job! Do you live in or around Chicago? Maybe you should come into the office and hang out, we get free lunches on Wednesdays and there are _always_ leftovers. 😉 

Seriously, though, drop me a line, if we share mutual friends then you should at least get free lunch out of it. 😄 

My work email: ppeble@sittercity.com

**Comment by morrme** [comment]
@ppeble you've got mail :)

**Comment by morrme** [comment]
@ppeble BTW it looks like codecov gives you the best of both worlds between coveralls and simplecov. May be worth testing out :)

**Comment by ppeble** [comment]
FYI, I simply turned off `coveralls`. We will check for above 99% coverage in `simplecov` now. Builds won't pass unless this is true.
