### ISSUE TITLE
Federal Holidays should be observed on Friday if they fall on Saturday

### ISSUE THREAD

**Issue by StephenWetzel** [holidays/holidays#274]
https://github.com/holidays/holidays/blob/master/lib/generated_definitions/federal_reserve.rb

The Federal Reserve definition uses to_monday_if_sunday(date), but should use to_weekday_if_weekend(date).  See the single asterix note on July 4, 2020 here:
https://www.federalreserve.gov/aboutthefed/k8.htm

> For holidays falling on Saturday, Federal Reserve Banks and Branches will be open the preceding Friday; however, the Board of Governors will be closed. For holidays falling on Sunday, all Federal Reserve offices will be closed the following Monday.

If not, then can we get a new definition for just "Federal" holidays that follow that convention?

**Comment by ppeble** [comment]
Thanks for the report! I completely agree. Seems like we should change the definition. I'll handle it over in https://github.com/holidays/definitions and try to get it out wit the v5.5.0 release(which should be out soonish).

Thanks again. Gonna leave this open until I get it done.

**Comment by StephenWetzel** [comment]
Hey, thanks for the fast response.  I realized I can get the behavior I want with the :us :observed definition.  I didn't realize that would exclude informal holidays at first.

I guess it's debatable if the :federal_reserve definition should have Saturday holidays observed on Fridays or not, since the banks are open, but the board is closed (see quoted paragraph).  Perhaps it would be worth splitting it up into a :federal_reserve_banks and :federal_reserve_board definitions.

**Comment by ppeble** [comment]
Hm....okay, I see what you mean. Unfortunately there are a lot of grey-ish areas in these definitions...at lot of it depends on what a person thinks for a specific situation. And it doesn't help that governments are constantly changing things. 😬 

I'll need to think a bit about this and do a bit more reading. Let me get back to you.

On a final note, your command about informal holidays is something that interests me. Perhaps I need to take that into account in our documentation...

**Comment by ppeble** [comment]
(and I'm not stalking you, I just had the tab still opened, that's why I responded within two minutes 😬 )

**Comment by StephenWetzel** [comment]
Yeah, great project overall, we were amazed to find NERC holidays in there.  I think aliases could be pretty useful honestly, I don't know how big of a change it would be in your implementation, but something that just aliases ":us_federal" to ":us :observed" would work.

Failing that, maybe just add this example to the documentation (you can never have enough examples):
```federal_holidays = Holidays.cache_between(Date.new(1900, 1, 1), Date.new(2100, 12, 31), :us, :observed)```

**Comment by sirwolfgang** [comment]
I do agree with having an alias to track us federal/banking holidays. I expect the use of holidays as it pertains to banking is a common enough use case to merit a configuration.

**Comment by poojawins** [comment]
I agree, it should be to_weekday_if_weekend(date). Federal law (5 U.S.C. 6103) establishes the following public holidays for Federal employees. Please note that most Federal employees work on a Monday through Friday schedule. For these employees, when a holiday falls on a nonworkday -- Saturday or Sunday -- the holiday usually is observed on Monday (if the holiday falls on Sunday) or Friday (if the holiday falls on Saturday). https://www.ca9.uscourts.gov/content/view.php?pk_id=0000000490

**Comment by mikecanann** [comment]
I think the fix for this is in my PR https://github.com/holidays/definitions/pull/87

At least it fixes it for me. I added a test case for moving the 4th of july to the 3rd for the year 2020.

**Comment by ppeble** [comment]
Whoops! This should have been closed! I thought that GH itself would close it because I referenced the issue but I guess not!

Thanks again for reporting!
