### ISSUE TITLE
Update with new definitions?

### ISSUE THREAD

**Issue by slucaskim** [holidays/holidays#277]
Hello, could we get an update of the holiday gems with the changes from this [PR](https://github.com/holidays/definitions/pull/38)? We are in sort of a tight need for this fix!

Thanks!

**Comment by ppeble** [comment]
Yes, sorry! I'll do it over lunch today. Thanks for poking me.

**Comment by ppeble** [comment]
Pushed! v5.6.0 has your changes. Thanks for your patience!
