### ISSUE TITLE
Version bump request

### ISSUE THREAD

**Issue by slucaskim** [holidays/holidays#283]
Hello, could we get a version bump to include this [definition fix](https://github.com/holidays/definitions/pull/63)? Thanks!

**Comment by ttwo32** [comment]
@slucaskim Oh, Sorry.
I will create a PR including [your PR](https://github.com/holidays/definitions/pull/63) and [another](https://github.com/holidays/definitions/pull/64) .
Thanks for your patience :)

**Comment by ppeble** [comment]
Yep, on it now. Thanks for your patience! We have some kind of issue with some holidays that I _think_ are unrelated but until I can hash it out I don't want to put out a new release. I'll provide an update as soon as I have one. 😄

**Comment by ppeble** [comment]
Oops, I didn't tag my PR with this issue. [v6.1.0](https://github.com/holidays/holidays/releases/tag/v6.1.0) is pushed to rubygems. It contains your fix. Thanks!

**Comment by ppeble** [comment]
Just want to say: this is the perfect way to poke us for a release! Thank you for keeping us from slipping. 😄
