### ISSUE TITLE
Version Bump Request

### ISSUE THREAD

**Issue by slucaskim** [holidays/holidays#286]
Hello, can we get a version bump of the definitions please?

Thanks!

**Comment by ttwo32** [comment]
Hi @slucaskim .
Sorry for delay.
I have created a PR . So , please wait a few days. 😄

**Comment by ppeble** [comment]
Sorry. This is entirely on me. Life, etc.

I'll do the bump now and also write up the MAINTAINERS guide for @ttwo32 tonight so we reduce the risk of this happening in the future. Sorry again.

**Comment by ppeble** [comment]
v6.2.0 is out. Thanks again for your patience.

@ttwo32 the MAINTAINERS guide is coming 😄
