### ISSUE TITLE
UK bank holiday missing

### ISSUE THREAD

**Issue by joecorkerton** [holidays/holidays#294]
The UK summer bank holiday at the end of August is missing. This falls on 27th August in 2017.

https://www.gov.uk/bank-holidays

**Comment by joecorkerton** [comment]
@ttwo32 Did you get a chance to look into this yet?

**Comment by ttwo32** [comment]
@joecorkerton Sorry for being so late in reply.
I couldn't get up from having caught a sick(influenza).

I have surveyed uk bank holidays.
"Summer bank holidays" is defined "Bank holidays" in gb.yaml
Please look at below link.

https://github.com/holidays/definitions/blob/master/gb.yaml#L68

And i have confirmed on console.

`
irb(main):040:0* Holidays.on( Date.civil(2017,8,28),[:gb_eng])
=> [{:date=>#<Date: 2017-08-28 ((2457994j,0s,0n),+0s,2299161j)>, :name=>"Bank Holiday", :regions=>[:gb_eng, :gb_wls, :gb_eaw, :gb_nir]}]
irb(main):041:0> 
`

This gem shows that 28th August in 2017 is "Bank Holiday".
And a site you teached me showed that 28th August in 2017 is "Summer Bank Holiday" .

Can i change name from "Bank Holiday" to "Summer Bank Holiday" ?

**Comment by joecorkerton** [comment]
@ttwo32 Thanks for your response. I thought the holiday is missing because I was searching for holidays using the `:gb` tag. Is there a reason that the `:gb` tag is not on this holiday? It seems like it should be added, as it is an official UK holiday

**Comment by ttwo32** [comment]
@joecorkerton Oh, sorry . I don,t know a reason. 
@ppeble Do you know a reasons that :gb tag is not on this holiday?

**Comment by timkrins** [comment]
@joecorkerton, @ttwo32  - easy one ;) 
28th August 2017 is not a holiday for Scotland, therefore it will not be in `:gb`
