### ISSUE TITLE
Israël support?

### ISSUE THREAD

**Issue by ssaunier** [holidays/holidays#300]
Hello 👋,

Thanks for the great gem! I was looking for a `il.rb` definition for Israël Holidays but could not find it. Is it another file, or is this country not yet supported?

Thank you!

**Comment by ttwo32** [comment]
@ssaunier Sorry for my slow response.
Unfortunately, there is no definition for Israel Holidays.
If it's fine with you, please make a Israel definition file and open a PR.
Contribution guide is [this](https://github.com/holidays/definitions/blob/master/CONTRIBUTING.md).

@ppeble Any thoughts?

**Comment by ppeble** [comment]
Sorry for the delay in response! 🙇‍♀️ 

Nope! The only reason that is no one has submitted one yet. I don't live in Israël so I haven't done it myself. PRs welcome!

**Comment by ppeble** [comment]
I'm closing this issue. As stated in the [CONTRIBUTING guide](https://github.com/holidays/holidays/blob/master/CONTRIBUTING.md#how-to-contribute) we rely on users from around the world to provide definitions for us. As a non-resident of the country I don't feel qualified to add anything, as we stated above.

Please feel free to submit a PR to the [definitions repository](https://github.com/holidays/definitions) and please check out our [CONTRIBUTING guide for the definitions](https://github.com/holidays/definitions/blob/master/CONTRIBUTING.md). Thank you!

**Comment by DagonWat** [comment]
Hi guys, I am now collecting data to create Israel holidays list. My company uses the gem and now we have a need. It will be ready soon.
