### ISSUE TITLE
Canadian Thanksgiving missing

### ISSUE THREAD

**Issue by joffet** [holidays/holidays#305]
Hi, great gem btw. Works great. Is it possible to get Canadian Thanksgiving? ( second Monday every October ) https://en.wikipedia.org/wiki/Thanksgiving_(Canada)

The others on my wishlist are Christmas Eve and New Years Eve in the informal category.

Thanks again for the fine work

**Comment by slucaskim** [comment]
Thanksgiving is already part of the list, are you experiencing it missing?
https://github.com/holidays/holidays/blob/master/lib/generated_definitions/ca.rb#L53

**Comment by joffet** [comment]
Ah, I see. I have to make the locale province specific. I guess there are some provinces that don't recognize it. Thanks

**Comment by ttwo32** [comment]
@slucaskim Thank you for answer this issue!!
@joffet Please feel free to ask more. :) 
Thanks!!
