### ISSUE TITLE
Federal reserve error for holidays in 2018

### ISSUE THREAD

**Issue by musa-raza** [holidays/holidays#312]
Hello, for federal reserve holidays, there is an error in your generator. Veterans day is on the 12th of November this year, not the 11th. https://www.newyorkfed.org/aboutthefed/holiday_schedule.html
<img width="520" alt="screen shot 2018-08-03 at 3 51 19 pm" src="https://user-images.githubusercontent.com/28770271/43662808-1e4c616e-9735-11e8-94d5-3cf8f3286167.png">

**Comment by jimryan** [comment]
@musa-raza See the [footnote](https://www.newyorkfed.org/aboutthefed/holiday_schedule.html#1) next to the 2018 date for Veteran's Day on the page you linked to.

It falls on November 11th this year, which is a Sunday, so it is _observed_ on Monday, November 12th.

If you want `Holidays` to return the dates holidays are observed, you need to pass the [observed](https://github.com/holidays/holidays#check-for-observed-holidays) flag, like so: `Holidays.year_holidays([:federal_reserve, :observed], Date.today)`

**Comment by musa-raza** [comment]
Thanks for the clarification @jimryan appreciate it
