### ISSUE TITLE
Bug in region generator

### ISSUE THREAD

**Issue by ghiculescu** [holidays/holidays#314]
Hey gang, https://github.com/TandaHQ/holidays/commit/16516dae449fc9a5af718ca8e0f1190df73aab43 shows a bug I found in the region generator.

Basically if a country came after its continent alphabetically, it might get the continent set as its parent region.

Our fork is pretty out of sync with upstream, but I would recommend at least cherry-picking this.

**Comment by ppeble** [comment]
Heya @ghiculescu! Sorry for the delay. Does https://github.com/holidays/holidays/pull/320 fix this? They look similar with slightly different approaches. Let me know what you think!

**Comment by ppeble** [comment]
I'm going to go ahead and close this one out, it seems like we are good. Please feel free to ping me so I can reopen if this didn't work for you!
