### ISSUE TITLE
Add valid year feature to holidays

### ISSUE THREAD

**Issue by hahahana** [holidays/holidays#33]
Holidays can be revoked, created, and changed so there should be functionality that specifies the validity of a holiday in certain years. For example, Memorial Day prior to 1971 had a different definition: instead of always falling on May 30 it was changed to the last Monday in May. We need functionality that can select the correct holidays based on the year. So if we are searching for holidays that fall between 1970 and 1971, we should have logic that filters out the holiday definition based on date.

Perhaps something like: 
  5: 
  - name: Memorial Day
    week: -1
    wday: 1
    regions: [federal_reserve]
    valid: <= 1970
  - name: Decoration Memorial Day
    mday: 30
    regions: [federal_reserve]
    valid: >= 1971

**Comment by ptrimble** [comment]
This has been implemented in https://github.com/holidays/holidays/pull/162

It will be merged son.

**Comment by ptrimble** [comment]
Addressed in above linked PR.
