### ISSUE TITLE
UK May Day still on the wrong day

### ISSUE THREAD

**Issue by jacobwalkr** [holidays/holidays#353]
Hi all,

Slightly niggly issue: although May Day has been moved to the 8th in holidays/definitions, there's no version of holidays (either through rubygems or github @ master) that reflects this.

Any idea when that change might make its way to rubygems? I'm working around it by forking atm :)

Cheers,
Jacob

**Comment by ttwo32** [comment]
Hi @jacobwalkr. Sorry for the lazy response.
UK May Day will be changed to May 8 only in 2020, right?
Perhaps it has already been fixed, so take a look this [PR](https://github.com/holidays/definitions/pull/142). :)

**Comment by jacobwalkr** [comment]
Hi @ttwo32 

No problem. Looks like there was a new release (8.0) made a few weeks after I posted this and it looks to have the newest version of the definitions.

Thanks :)
