### ISSUE TITLE
Release 8.0.0 missing from GitHub?

### ISSUE THREAD

**Issue by dbastin** [holidays/holidays#356]
Just wondering about some strangeness around the latest GitHub release version not matching the RubyGems.org release version pushed by @ppeble on 09/25/19. 

Latest GitHub release: v7.1.0 (https://github.com/holidays/holidays/releases)
Latest RubyGems release: v8.0.0 (https://rubygems.org/gems/holidays)

Perhaps an oversight(?), but wanted to confirm.

**Comment by ricardo-motorefi** [comment]
I noticed this as well...

**Comment by ttwo32** [comment]
@dbastin @ricardo-motorefi Sorry for lazy response.
I have corrected a release information of Github.
Thanks!!
