### ISSUE TITLE
Missing Mayday for Germany Subregion Berlin

### ISSUE THREAD

**Issue by Bussinho** [holidays/holidays#361]
Hi there,

the 8th of May on 2020 is a holiday in Germany/Berlin, this is not considered in the gem.
This holiday is a unique holiday called "Liberation Day" and only in the year 2020.
Please check on the official homepage of Berlin:
https://www.berlin.de/tourismus/infos/1887651-1721039-feiertage-schulferien.html

Thanks,
Andre

**Comment by ttwo32** [comment]
Hi @Bussinho !!
Holidays gem consider 'the 8th of May on 2020'.
`irb(main):003:0> Holidays.on( Date.civil(2020,5,8),:de_be)
=> [{:date=>#<Date: 2020-05-08 ((2458978j,0s,0n),+0s,2299161j)>, :name=>"Tag der Befreiung", :regions=>[:de_be]}]`
