### ISSUE TITLE
4 day UK Bank Holiday in 2022

### ISSUE THREAD

**Issue by hlascelles** [holidays/holidays#372]
It looks like there may be an extra day's holiday in the UK in 2022: https://www.bbc.com/news/uk-54911550

```
A "once-in-a-generation show" over a four-day bank holiday weekend will mark the Queen's Platinum Jubilee in 2022.

The Queen, 94, hopes as many people as possible across the UK will have the opportunity to join the celebrations, Buckingham Palace said.

She will have reigned for 70 years on 6 February 2022 but plans are in place to stage a series of events from 2-5 June.
```

If we don't add it to this gem she'll cut our heads off.

**Comment by hlascelles** [comment]
This is now official (and less than a year away): https://www.gov.uk/bank-holidays

Is it easy to add? Would you like a PR @ttwo32?

![image](https://user-images.githubusercontent.com/299102/120923937-1bad4b00-c6c9-11eb-9c14-cc5d2554e320.png)

**Comment by hlascelles** [comment]
@ttwo32 What do you think? This is less than a year away and may be affecting financial apps calculations.

```ruby
❯ gem install holidays  
Fetching holidays-8.4.1.gem
Successfully installed holidays-8.4.1

irb(main):004:0> Holidays.on(Date.civil(2022, 6, 2), :gb)
=> []
irb(main):005:0> Holidays.on(Date.civil(2022, 6, 3), :gb)
=> []

```

**Comment by ttwo32** [comment]
I'm really sorry for the delay in my response.
It needs to update uk yaml delinifition.
Would you please read the guide and send us a PR?

https://github.com/holidays/holidays/blob/master/doc/CONTRIBUTING.md#for-definition-updates

**Comment by owst** [comment]
@ttwo32 it looks like https://github.com/holidays/definitions/pull/207 will address this issue
