### ISSUE TITLE
Release a new version to allow this gem to be used with Ruby 3.0

### ISSUE THREAD

**Issue by yevhene** [holidays/holidays#376]
Please

**Comment by ttwo32** [comment]
@yevhene We allow holidays gem to be used with Ruby 3.0.

Please check PR https://github.com/holidays/holidays/pull/370

**Comment by yevhene** [comment]
@ttwo32 In master. But release a version in RubyGems please

**Comment by ttwo32** [comment]
I have released version 8.4 in 12/2020.
This version contained a PR https://github.com/holidays/holidays/pull/370 .

**Comment by yevhene** [comment]
@ttwo32 Thanks! Missed it without letter `v` in tag
