### ISSUE TITLE
Abuse - very important - iso8583

### ISSUE THREAD

**Issue by aleksandersotnikov** [holidays/holidays#384]
Good day, Boris Stall! 

Please remove the old project  https://github.com.cnpmjs.[]org/smartkiosk/iso8583-mkb from public access.  
The project contains confidential information for Bank.
This is very important!

URL:
https://github.com/smartkiosk/iso8583-mkb
https://github.com/smartkiosk/distribution/blob/90deae0e5501a392275edd7fac4778625ff8830f/installer.sh

**Comment by ppeble** [comment]
This looks like spam. Closing.
