### ISSUE TITLE
Version Bump Request

### ISSUE THREAD

**Issue by drhie** [holidays/holidays#385]
Hi,
Can we get a version bump of the definitions please?
There is a Canadian holiday coming up in Sept 30 that we will need this for.
Thanks!

**Comment by Murphydbuffalo** [comment]
@ppeble hi and thanks for the awesome gem! Using the latest version of `definitions` would be awesome as [it includes the new US federal holiday Juneteenth](https://github.com/holidays/definitions/pull/195)

**Comment by Xipher7934** [comment]
+1. There have been additions to the definitions that are important.

**Comment by ttwo32** [comment]
@drhie @Murphydbuffalo @Xipher7934 I'm really sorry for my lazy response...
I have released  ver 8.5.0.
Would you please update a holidays gem for your apps?
