### ISSUE TITLE
Queen Elizabeth II passing Bank Holiday

### ISSUE THREAD

**Issue by hlascelles** [holidays/holidays#398]
There will be a bank holiday in remembrance of HM QEII. The date is not concrete yet, so this is an issue placeholder. It is likely to be Monday 19th September 2022.

https://www.bbc.co.uk/news/uk-62862225

**Comment by ttwo32** [comment]
@hlascelles Thank you for letting me know that.:)
If you don't mind, could you please submit a PR at [holidays/definitions](https://github.com/holidays/definitions)?

**Comment by justinjones** [comment]
@ttwo32 I've updated the definitions for the AU version of this holiday: https://github.com/holidays/definitions/pull/232

**Comment by hlascelles** [comment]
Added... https://github.com/holidays/definitions/pull/235

Also, a fix for the KE holidays: https://github.com/holidays/definitions/pull/236

**Comment by Jonic** [comment]
@hlascelles Thanks for the speedy update!

Does this still count as having been fixed without an updated release of this Gem? Without your PR merging to `definitions`, and a new release of the Gem, technically this issue hasn't been resolved yet, but closing this issue might give the impression that it has been. Should this issue stay open until a new release has been published?

In the meantime I've taken the additional config you've added to manually provide a definition in our app, but hopefully there'll be a new release of the Gem before then.

**Comment by WorkSutton** [comment]
@hlascelles Looks like this can be closed now as the PR has been merged in the definitions file and this commit https://github.com/holidays/holidays/commit/ed17774be9b7c31e4da1374aba1d0b7fa2e701c8 pulled it altogether.

Only thing I cannot see is a new tagged/released version has not been pushed even though the version has changed.

**Comment by ppeble** [comment]
It has been pushed, the version is `v8.6.0` in rubygems. I will update this releases page, sorry about it! Please try pulling it and let us know if it works for you!

**Comment by WorkSutton** [comment]
@ppeble Yes I was able to pull the gem using `bundle update holidays --conservative` and it update from 8.5.0 to 8.6.0.

I just expected to see a tag in releases/tags, but maybe I was confused on that.

Thanks for getting this merged in and published today. Very much appreciated 👍

**Comment by ppeble** [comment]
No, you aren't wrong, I had to add it just now. That's why you couldn't see it, I forgot! Thanks for reminding me. 🙇

**Comment by hlascelles** [comment]
Thanks for the gem release! :+1:
