### ISSUE TITLE
Move Date monkey patching out of the main lib

### ISSUE THREAD

**Issue by alexdunae** [holidays/holidays#61]
Monkey patching `Date` should be deprecated, then eventually moved into a `core_extension` file for optional inclusion.  Monkey patching was cool in 2007, but not so much now.

**Comment by aripollak** [comment]
I would like this! Would a PR to do this be accepted? Obviously this would be a breaking change so the major version number would have to be incremented to adhere to semantic versioning.

Somewhat relatedly, is there any reason that holidays.rb ends up `include`ing Holidays inside Date? It doesn't look like that should have any useful effect.

**Comment by ptrimble** [comment]
@aripollak Of course! I don't mind a major bump, it would be a nice addition.

To your question, I don't think you'll get an answer on why it was done that way. It was a long time ago. If it works without it then I think we're good to go.

**Comment by ptrimble** [comment]
FYI for anyone working on this, I am going to roll this update into my [refactor](https://github.com/ptrimble/holidays/tree/refactor) branch. Should have something up today.

**Comment by ptrimble** [comment]
And it's done. I'm going to leave this issue open until we actually merge in the overall refactor just so I don't lose track of it.

Feedback welcome: https://github.com/ptrimble/holidays/blob/refactor/lib/holidays/core_extensions/date.rb

You can check out the updated README on my branch as well for usage.

**Comment by ptrimble** [comment]
This has been merged.
